---
name: hostinfo

releases:
- {name: hostinfo, version: latest}

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: hi
  azs: [z1]
  vm_type: default
  instances: 2
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: hostinfo
    templates:
    - {name: hostinfo, release: hostinfo}


