---
name: bosh-simple

releases:
- name: bosh-simple
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  azs: [z1]
  properties: {}
