---
name: bosh-simple

releases:
- name: bosh-simple
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: app
  instances: 1
  azs: [z1]
  jobs:
  - name: app
    release: bosh-simple
    properties:
      port: 8080
    templates:
    - name: app
  vm_type: default
  stemcell: default
  networks:
  - name: default

