---
name: bosh-simple

releases:
- name: bosh-simple
  version: latest

networks:
- name: default
  subnets:
  - range: 10.0.0.0/22
    reserved: [10.0.0.1,10.0.0.6]
    static: [10.0.0.11,10.0.0.12,10.0.0.13]

resource_pools:
- name: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  network: default

compilation:
  workers: 2
  network: default

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.0.0.11
  properties: {}
